### ISSUE TITLE
Add hint to code snippets if viewed inside IntelliJ

### ISSUE THREAD

**Issue by itsandreramon** [jdubois/azure-native-spring-function#4]
The code snippets are not rendered correctly inside the integrated markdown viewer of IntelliJ IDEA (2020.3)

Code inside IntelliJ

![Screenshot 2021-03-10 at 11 58 33](https://user-images.githubusercontent.com/17139385/110619322-f6777200-8197-11eb-9a48-23401a42fbec.png)

vs actual (GitHub)

![Screenshot 2021-03-10 at 11 59 11](https://user-images.githubusercontent.com/17139385/110619391-0c853280-8198-11eb-86c2-cf02d6d51848.png)

Will file a bug for IntelliJ eventually as well..

**Comment by jdubois** [comment]
Indeed, it's an Intellij bug, I can't do much to fix it from here. Anyway, the documentation is supposed to be read on GitHub.

I'm closing this as I just can't do anything on my side, but it's good to know.
